 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
     try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
	
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $this->auth()->isLoggedIn())); ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", array('%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
 
 
 <? if (count($holdings) > 1) : ?>
	<div id="holdings_tabs">
		<ul>
	<? if (!empty($urls) || $openUrlActive): ?>
  		<li><a href="#holdings_tab-internet"><?=$this->transEsc("Internet")?></a></li>
	<? endif; ?>
  <? $h_counter=1;?>
	<? foreach ($holdings as $holding): ?>
		<? if ($holding['location'] != 'Via INTERNET'):?>
			<li><a href="#holdings_tab-<?=$h_counter?>">
  			<? $locationText = $this->transEsc('location_' . $holding['location'], array(), $holding['location']); ?>
  			<!-- not using  the  $holding['locationhref'] value to create a link so we can keep the tabs-->
    		<?=$locationText?>
			</a></li>
		<? endif; ?>
	<? $h_counter++;?>
	<? endforeach; ?>
	</ul>
<? elseif (count($holdings) ==1):?>
	<? foreach ($holdings as $holding):?>
		<? if (!empty($holding['location'])):?>
			<? $locationText = $this->transEsc('location_' . $holding['location'], array(), $holding['location']); ?>  			
	    	<h4><?=$locationText?></h4>
		<? endif;?>
	<? endforeach;?>
<? endif;?>

<? if (!empty($urls) || $openUrlActive): ?>
<div id="holdings_tab-internet">
  <? if (!empty($urls)): ?>
    <? foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <? endforeach; ?>
  <? endif; ?>
  <? if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><? endif; ?>
</div>
 <? endif; ?>
 <? $h_counter=1;?>
<? foreach ($holdings as $holding): ?>
<? if ($holding['location'] != 'Via INTERNET'):?>
<div id="holdings_tab-<?=$h_counter?>">
<table class="table table-striped" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
  <? $callNos = $this->tab->getUniqueCallNumbers($holding['items']); if (!empty($callNos)): ?>
  <tr>
    <th><?=$this->transEsc("Call Number")?>: </th>
    <td width="50%">
      <? foreach ($callNos as $callNo): ?>
        <? if ($this->callnumberHandler): ?>
          <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
        <? else: ?>
          <?=$this->escapeHtml($callNo)?>
        <? endif; ?>
        <br />
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? if (isset($holding['textfields'])): foreach ($holding['textfields'] as $textFieldName => $textFields): ?>
    <tr>
      <? // Translation for summary is a special case for backwards-compatibility ?>
      <th><?=$textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?>:</th>
      <td>
        <? foreach ($textFields as $current): ?>
          <?=$this->escapeHtml($current)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endforeach; endif; ?>
<? $itemRow = 1;?>
  <? foreach ($holding['items'] as $row): ?>
    <?
      // AJAX Check record?
      $check = isset($row['check']) && $row['check'];
      $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
      $checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
      // AJAX block record?
      $block = !$check && isset($row['addLink']) && $row['addLink'] === 'block';
      $blockStorageRetrievalRequest = !$checkStorageRetrievalRequest && isset($row['addStorageRetrievalRequestLink']) && $row['addStorageRetrievalRequestLink'] === 'block';
      $blockILLRequest = !$checkILLRequest && isset($row['addILLRequestLink']) && $row['addILLRequestLink'] === 'block';
    ?>
    <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
    	<? if ($itemRow > 10 && (count($holding['items']) > 10)):?>    
      		<tr vocab="http://schema.org/" typeof="Offer" class="more">      		
    	<? else: ?>
    		<tr vocab="http://schema.org/" typeof="Offer">
     	<? endif; ?>     
        <th><!--<?=$this->transEsc("Copy")?>--> <?=$this->escapeHtml($row['number'])?></th>
        <td>
          <? if ($row['reserve'] == "Y"): ?>
            <link property="availability" href="http://schema.org/InStoreOnly" />
            <? if ($row['status'] == 'e'): ?>
            <?=$this->transEsc("Ask at Spec")?><br />
            <? else: ?>
            <?=$this->transEsc("Ask at Circulation Desk")?><br />
            <? endif; ?>
          <? endif; ?>
          <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>
               <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
              <? if (!$block && isset($row['link']) && $row['link']): ?>
                <a class="<?=$check ? 'checkRequest ' : ''?>placehold" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
              <? endif; ?>
              <? if (!$blockStorageRetrievalRequest && isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <? endif; ?>
              <? if (!$blockILLRequest && isset($row['ILLRequestLink']) && $row['ILLRequestLink']):?> 
              	<? $authors = $this->driver->getDeduplicatedAuthors();?>
              	<? $publications = $this->driver->getPublicationDetails();?>
			  	<? if (!empty($publications)) :?>
			  		<? $pubName = $publications[0]->getName(); ?>
			  		<? $pubDate = $publications[0]->getDate(); ?>
			  	<? endif; ?> 
			  	<? if (!empty($authors['main'])):?>
			  		<? $author_name = $authors['main'][0];?>
			  	<? else:?>
			  		<? $author_name = '';?>
			  	<? endif; ?>
              	<? $illiadURL = urlencode("&aulast=".rawurlencode(($author_name))."&title=".rawurlencode($this->driver->getShortTitle(). ' ' . $this->driver->getSubtitle())."&date=".$pubDate."&pub=".$pubName."&edition=".$this->driver->getEdition()."&ESPNumber=".$this->driver->getCleanOCLCNum()."&isbn=".$this->driver->getCleanISBN()); ?>
      			<? $webbridgeLink = $row['ILLRequestLink'].'?returnurl=http://'.$_SERVER['HTTP_HOST'].$this->recordLink()->getUrl($this->driver->getUniqueId()).'&resurl=https%3A%2F%2Funl.illiad.oclc.org%2Filliad%2Filliad.dll%2FOpenURL%3Fsid%3DUNLcat%26genre%3DBook'.$illiadURL.'&resname=Request+Item&linkid=0&linkloc=item'?>
                <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>inlineblock modal-link placeILLRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($webbridgeLink)?>"  title="<?=$this->transEsc("Request item")?>">&nbsp;<?=$this->transEsc("Request item")?></a>
              <? endif; ?>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <span class="text-danger">
                <? if ($row['status']=='-'): ?>
                	Checked out
                <? else: ?><?=$this->transEsc($row['status'])?>
                <? endif; ?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
              <? if (!$block && isset($row['link']) && $row['link']): ?>
                <a class="<?=$check ? 'checkRequest' : ''?> placehold" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
              <? endif; ?>
            <? endif; ?>
            <? if (isset($row['item_notes'])): ?>
              <div class="item-notes">
                <b><?=$this->transEsc("Item Notes")?>:</b>
                <ul>
                  <? foreach ($row['item_notes'] as $item_note): ?>
                    <li><?=$this->escapeHtml($item_note) ?></li>
                  <? endforeach; ?>
                </ul>
              </div>
            <? endif; ?>
          <? endif; ?>
          <? /* Embed item structured data: library, barcode, call number */ ?>
          <? if ($row['location']): ?>
            <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
          <? endif; ?>
          <? if ($row['barcode']): ?>
            <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
          <? endif; ?>
          <? if ($row['callnumber']): ?>
            <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
          <? endif; ?>
          <? /* Declare that the item is to be borrowed, not for sale */ ?>
            <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
            <link property="itemOffered" href="#record" />
        <? if ($itemRow == 10 &&(count($holding['items']) > 10)):?>
      		<a href="" id="morelink" class="more_rows">Show more items +</a>
      	<? elseif (($itemRow == count($holding['items'])) && (count($holding['items']) > 10)): ?>
      		<a href="" id="lesslink" class="more_rows">Show less items -</a>
      	<? endif;?>
        </td>

      </tr>
        <? $itemRow++;?>
    <? endif; ?>  
  <? endforeach; ?>
  <? if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>
</div>
<? endif; ?> <!--  end if location is Via INTERNET -->
<? $h_counter++;?>
<? endforeach; ?>
 <? if ((count($holdings) > 1) || (count($holdings) == 1 && !empty($holdings[0]['location']))) : ?>
</div> <!--  end of holdings_tabs div -->
<? endif;?>
<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table table-striped">
  <? foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>


<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script>
$(function() {
	<? if (count($holdings) > 1): ?>
    $( "#holdings_tabs" ).tabs();
    <? endif;?>
     
    var moretext = "Show more +";
    var lesstext = "Show less";    
  
 	$(".more").hide();
    $("#morelink").click(function(){
        $(this).hide();
        $("#lesslink").show();
        $(".more").toggle();        
        return false;
    });
    $("#lesslink").click(function(){
    	$(this).hide();
    	$("#morelink").show();
    	$(".more").toggle();
    	return false;
    });
});

</script>
<style>
.more_rows{float:right;}
</style>
