<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'VufindUNL\RecordDriver\Factory'     => __DIR__ . '/src/VufindUNL/RecordDriver/Factory.php',
    'VufindUNL\RecordDriver\SolrMarc'    => __DIR__ . '/src/VufindUNL/RecordDriver/SolrMarc.php',
    'VufindUNL\RecordDriver\EIT' => __DIR__ . '/src/VufindUNL/RecordDriver/EIT.php',
    'VufindUNL\Module'                   => __DIR__ . '/Module.php',
);
